name: "Image Actions"
author: "mathieudutour"
description: "Compresses Images for the Raycast Extensions repo"

inputs:
  jpegQuality:
    description: "JPEG quality level"
    required: false
    default: "80"

  jpegProgressive:
    description: "Use progressive (interlaced) scan for JPEG"
    required: false
    default: "false"

  pngQuality:
    description: "PNG quality level"
    required: false
    default: "80"

  webpQuality:
    description: "WEBP quality level"
    required: false
    default: "80"

  images:
    description: "Comma separated list of images to compress"
    required: true

outputs:
  markdown:
    description: "Output param used to store the Markdown summary for subsequent actions to use"

runs:
  using: "docker"
  image: "docker://ghcr.io/mathieudutour/image-actions/image-actions:main"

branding:
  icon: "image"
  color: "green"
